### ISSUE TITLE
Is this plugin compatible with Microsoft SQL Server?

### ISSUE THREAD

**Issue by Kenery** [jazz-community/rtc-statushistory-presentation#14] opened 2018-05-21 02:36 UTC
Hi All,

We have applied this wonderful plugin to our RTC 6.0.2 for a while and it worked like a charm. But last week after migrating our database from IBM DB2 to Microsoft SQL Server, we cannot see the status history presentation anymore. I'd like to check if this plugin is constrained in IBM DB2? Thanks.

**Comment by schneigu** [comment] 2018-05-21 12:52
There is no reason why it should not work wirh SQLserver backend.

**Comment by schneigu** [comment] 2018-05-21 12:53
(But why have you changed from DB2 to SQLserver at all.) Other discussion. Just wondering.

**Comment by innerjoin** [comment] 2018-05-21 20:25
Hi @Kenery, apart from the database migration, was there any other change that you did that is closer to the application layer? (e.g. upgrading to another version, changing process templates, ...)
Could you check the browser console and network tab for any errors or failing requests? This might help us to narrow down the issue

**Comment by innerjoin** [comment] 2018-08-08 11:39
@Kenery Please excuse my late response. This could have been caused by #12. If yes, this would be fixed with [Version 2.2.5](https://github.com/jazz-community/rtc-statushistory-presentation/releases/tag/v2.2.5). Please let me know if this solves your issue, thanks.

**Comment by innerjoin** [comment] 2018-09-04 20:05
Closing this issue as there hasn't been any reply by the opener

**Closed as completed by innerjoin** 2018-09-04 20:05 UTC
Labels: help wanted, needs investigation
